apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    component: spark-master
spec:
  type: NodePort
  ports:
  - port: 7077
    targetPort: 7077
    nodePort: 30077 
    name: spark-master
  - port: 8080
    targetPort: 8080
    nodePort: 30080 
    name: spark-master-web
  selector:
    component: spark-master